In [1]:
import pandas as pd
import numpy as np

In [3]:
import pandas as pd

data = pd.read_csv("/content/drive/MyDrive/Worksheet5/student.csv")

print("First 5 rows of the DataFrame:")
data.head()

First 5 rows of the DataFrame:


Math  Reading  Writing
0    48       68       63
1    62       81       72
2    79       80       78
3    76       83       79
4    59       64       62

In [4]:
print("\nLast 5 rows of the DataFrame:")
data.tail()


Last 5 rows of the DataFrame:


Math  Reading  Writing
995    72       74       70
996    73       86       90
997    89       87       94
998    83       82       78
999    66       66       72

In [5]:
# Information of Dataset
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Math     1000 non-null   int64
 1   Reading  1000 non-null   int64
 2   Writing  1000 non-null   int64
dtypes: int64(3)
memory usage: 23.6 KB


In [6]:
# Descriptive information
data.describe()

Math      Reading      Writing
count  1000.000000  1000.000000  1000.000000
mean     67.290000    69.872000    68.616000
std      15.085008    14.657027    15.241287
min      13.000000    19.000000    14.000000
25%      58.000000    60.750000    58.000000
50%      68.000000    70.000000    69.500000
75%      78.000000    81.000000    79.000000
max     100.000000   100.000000   100.000000

In [7]:
# Feature X and label Y

X = data[['Math', 'Reading']].values
Y = data['Writing'].values

print("Feature X: ")
print(X)
print("Label Y:")
print(Y)

Feature X: 
[[48 68]
 [62 81]
 [79 80]
 ...
 [89 87]
 [83 82]
 [66 66]]
Label Y:
[ 63  72  78  79  62  85  83  41  80  77  64  90  45  77  70  46  76  44
  85  72  53  66  75  49  84  83  68  66  77  78  74  83  72  65  46  66
  50  79  68  46  86  70  61  53  72  75  50  77 100  81 100  87  78  48
  50  44  48  43  67  78  58  91  92  78  42  85  73  83  61  58  60  55
  48  62  68  59  62  48  74  63  80  79  73  79  45  67  89  77  81  88
  53  68  79  77  63  73  60  67 100  79  26  51  80  57  41  78  68  49
  76  41  71  77  89  86  55  80  56  74  85  80  73  74  86  56  53  44
  41  59  71  81  74  78  67  53  56  75  82  79  99  76  59  96  75  61
  56  88  65 100  79  55  61  83  74  59  54  47  82  74  59  74  84  59
  43  65  61  78  84  73  73  92  63  72  61  59  70  87  78  65  73  62
  69  55  73  63  67  86  78  85  83  80  60  90  56  70  55  80  82  60
  78  76  94  75  68  71  85  46  58  46  84  58  57  59  77  63  68  99
  48  91  57  80  46  75  59  87  82  79  6

In [8]:
# Create matrices: Y = w^T * X

import numpy as np

w = np.random.rand(X.shape[1])

# matrix multiplication: Y = w^T  * X
Y_pred = np.dot(X, w)

print("Feature Matrix (X):")
print(X)

print("\nWeight Vector (W):")
print(w)

print("\nPredicted Labels (Y_pred):")
print(Y_pred)

Feature Matrix (X):
[[48 68]
 [62 81]
 [79 80]
 ...
 [89 87]
 [83 82]
 [66 66]]

Weight Vector (W):
[0.03205973 0.95792037]

Predicted Labels (Y_pred):
[66.6774517  79.57925262 79.16634759 81.94392951 63.19842723 82.6774318
 82.70949152 47.45492494 76.6734318  77.47492494 68.08420823 86.60529244
 43.94384074 77.31462632 69.01006887 43.71942266 69.93592951 47.42286521
 88.48907344 74.24850686 57.67532311 65.05014851 71.11826796 51.83162174
 84.5612128  88.39289426 65.21044714 73.63937207 77.34668604 80.60129244
 76.03610869 88.42495399 72.93792951 68.5330444  41.23037827 59.93994942
 52.37276567 76.16434759 73.09822814 43.49500457 85.6794318  76.26052677
 61.47494485 48.57314394 67.09422814 71.18238741 52.4048254  72.93792951
 98.67741189 72.74557116 98.99800915 87.59527253 79.57925262 50.29662631
 49.4028254  48.63726339 54.67332311 49.46694485 68.56510412 79.83573043
 54.60920366 90.75757116 97.08216842 81.81569061 43.17827873 90.91786979
 66.93392951 82.58512403 59.6552833  57.675323

In [9]:
# Split the dataset into training and test sets
# 80 % for training and 20 % for testing

from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# Show the results
print("Training Features (X_train):")
print(X_train)
print("\nTest Features (X_test):")
print(X_test)
print("\nTraining Labels (Y_train):")
print(Y_train)
print("\nTest Labels (Y_test):")
print(Y_test)


Training Features (X_train):
[[64 82]
 [62 70]
 [36 21]
 ...
 [64 76]
 [66 75]
 [68 76]]

Test Features (X_test):
[[ 63  69]
 [ 42  37]
 [ 69  62]
 [ 69  59]
 [100  92]
 [ 60  70]
 [ 90  99]
 [ 38  50]
 [ 68  60]
 [ 94  79]
 [ 79  87]
 [ 62  67]
 [ 72  69]
 [ 42  58]
 [ 68  59]
 [ 65  56]
 [ 71  71]
 [ 51  69]
 [ 77  89]
 [ 70  65]
 [ 71  82]
 [ 59  74]
 [ 72  66]
 [ 84  74]
 [ 65  57]
 [ 75  88]
 [ 51  53]
 [ 65  66]
 [ 83  85]
 [ 51  44]
 [ 93  97]
 [ 90  84]
 [ 40  32]
 [ 54  55]
 [ 88  87]
 [ 63  76]
 [ 95  89]
 [ 77  85]
 [ 63  75]
 [ 70  81]
 [ 90  76]
 [ 49  62]
 [ 51  61]
 [ 62  72]
 [ 62  59]
 [ 84  80]
 [ 60  84]
 [ 73  85]
 [ 43  39]
 [ 77  80]
 [ 43  54]
 [ 58  73]
 [ 64  64]
 [ 66  69]
 [ 63  52]
 [ 71  77]
 [ 42  36]
 [ 62  69]
 [ 71  74]
 [ 96  89]
 [ 46  50]
 [ 47  50]
 [ 73  61]
 [ 49  66]
 [ 61  63]
 [ 99  89]
 [ 93 100]
 [ 77  70]
 [ 68  61]
 [ 79  86]
 [ 47  44]
 [ 86  99]
 [ 57  62]
 [ 77  81]
 [ 68  66]
 [ 53  64]
 [ 92  82]
 [ 42  44]
 [ 67  68]
 [ 48  45]
 [ 75 

In [10]:
# Build a cost function

def cost_function(X, Y, w):
  """Parameters:
  This function finds the Mean Square Error.
  Input parameters:
    X : Feature Matrix ()
    Y : Target Matrix
    w : Weight Matrix
  Output:
    cost : accumulated Mean Square Error
  """
  # number of samples
  m = X.shape[0]
  # predicted values (w^T * X)
  Y_pred = np.dot(X, w)
  # Mean Square Error : (Y-pred(i) - Y(i))^2 ; where Y-pred(w) = w^T * X
  cost = np.sum((Y_pred - Y)**2) / (2 * m)
  return cost

cost_value = cost_function(X, Y, w)
print("Cost Value:", cost_value)

Cost Value: 10.73346886477537


In [11]:
# Test case
def cost_function(X, Y, w):
  """Parameters:
  This function finds the Mean Square Error.
  Input parameters:
    X : Feature Matrix ()
    Y : Target Matrix
    w : Weight Matrix
  Output:
    cost : accumulated Mean Square Error
  """
  # number of samples
  m = X.shape[0]
  # predicted values (w^T * X)
  Y_pred = np.dot(X, w)
  # Mean Square Error : (Y-pred(i) - Y(i))^2 ; where Y-pred(w) = w^T * X
  cost = np.sum((Y_pred - Y)**2) / (2 * m)
  return cost

X_test = np.array([[1, 2], [3, 4],[5, 6]])
Y_test = ([3, 7, 11])
w_test = np.array([1, 1])

cost = cost_function(X_test, Y_test, w_test)

if cost == 0:
  print("Proceed Further")
else:
  print("Error in Cost Function")
print("Cost Function Value:", cost)

Proceed Further
Cost Function Value: 0.0


In [12]:
from typing import final
# Gradient Descent

def gradient_descent(X, Y, w, alpha, iterations):
  """Perform gradient descent to optimize the parameters of a linear regression model.
  Parameters:
    X : Feature Matrix (m,n)
    Y : Target Matrix (m,1)
    w : Initial guess for parameters(n,1)
    alpha (float) : learning rate
    iterations (int) : number of iterations for gradient descent.
  Returns:
  tuple: A tuple containing the final optimized parameters(W_update) and the history of cost values.
  w_update : Updated parameters (n,1)
  cost_hitory : History of cost values
  """
  cost_history = [0] * iterations
  # Number of samples
  m = len(Y)

  # w_update = initial weight at first
  w_update = w
  for iteration in range(iterations):
    # Step 1: Hypothesis values
    Y_pred = np.dot(X, w_update)

    # Step 2: Difference between Hypothetis and Actual Y
    loss = Y_pred - Y

    # Step 3: Gradient Calculation
    dw = (1 / m) * np.dot(X.T, loss)

    # Step 4: Updating value of w using gradient
    w_update = w_update - alpha * dw

    # Step 5: New cost value
    cost = cost_function(X, Y, w_update)

    cost_history[iteration] = cost

  return w_update, cost_history

# Test case
np.random.seed(0)
X = np.random.rand(100, 3)
Y = np.random.rand(100)
w = np.random.rand(3)

alpha = 0.01 # learning rate
iterations = 1000 # number of iterations

final_parameters, cost_history = gradient_descent(X, Y, w, alpha, iterations)

print("Final Parameters:", final_parameters)
print("Cost History:", cost_history)


Final Parameters: [0.20551667 0.54295081 0.10388027]
Cost History: [0.10711197094660153, 0.10634880599939901, 0.10559826315680616, 0.10486012948320558, 0.1041341956428534, 0.10342025583900626, 0.1027181077540776, 0.1020275524908062, 0.10134839451441931, 0.1006804415957737, 0.1000235047554587, 0.09937739820884377, 0.09874193931205609, 0.09811694850887098, 0.09750224927850094, 0.0968976680842672, 0.09630303432313951, 0.09571818027612913, 0.09514294105952065, 0.09457715457692842, 0.09402066147216397, 0.09347330508290015, 0.09293493139511913, 0.09240538899833017, 0.09188452904154543, 0.0913722051899995, 0.09086827358260123, 0.09037259279010502, 0.08988502377398917, 0.08940542984603007, 0.08893367662855953, 0.08846963201539432, 0.08801316613342668, 0.08756415130486386, 0.08712246201010665, 0.08668797485125507, 0.08626056851623205, 0.08584012374351278, 0.08542652328745133, 0.08501965188419301, 0.0846193962181636, 0.08422564488912489, 0.08383828837978763, 0.08345721902397185, 0.08308233097530

In [16]:
# Evaluate the model

def rmse(Y , Y_pred):
  """
  This function calculates the Root Mean Squares.
  Input Arguments:
  Y : Array of actual (target) dependent variables
  Y_pred : Array of predicted dependent variables
  Output Arguments:
  rmse : Root Mean Squares
  """
  mse = np.mean((Y - Y_pred) ** 2)
  rmse = np.sqrt(mse)
  return rmse

# Test case
np.random.seed(0)
Y = np.random.rand(100)
Y_pred = np.random.rand(100)  # Simulated predictions

result = rmse(Y, Y_pred)
print("Root Mean Squared Error (RMSE): ", result)

Root Mean Squared Error (RMSE):  0.41628103800387234


In [18]:
# Model evaluation - r2
# here, r2 = 1 - (residual sum of squares / total sum of squares)
# where, residual sum squares = (Y - Y_pred)^2
# and, total sum squares = (Y - Mean_Y)^2

def r2(Y, Y_pred):
  """
  This function calculates the R squared value.
  Input Arguments:
  Y : Array of actual (target) dependent variables
  Y_pred : Array of predicted dependent variables
  Output Arguments:
  r2 : R squared value
  """

  mean_y = np.mean(Y)
  # Total sum of squares
  ss_total = np.sum((Y - mean_y) ** 2)
  # Residual sum of squares
  ss_residual = np.sum((Y - Y_pred) ** 2)
  # R squared value
  r2 = 1 - (ss_residual / ss_total)
  return r2

# Test case
np.random.seed(0)
Y = np.random.rand(100)       # Actual values
Y_pred = np.random.rand(100)  # Predicted values

result = r2(Y, Y_pred)
print("R squared (R2): ", result)

R squared (R2):  -1.084870754292952


In [21]:
# Main function

def main():
  data = pd.read_csv("/content/drive/MyDrive/Worksheet5/student.csv")

  X = data[['Math', 'Reading']].values
  Y = data['Writing'].values

  X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

  w = np.zeros(X.shape[1])
  alpha = 0.00001
  iterations = 1000

  w_optimal, cost_history = gradient_descent(X_train, Y_train, w, alpha, iterations)

  Y_pred = np.dot(X_test, w_optimal)
  Y_train_pred = np.dot(X_train, w_optimal)

  train_rmse = rmse(Y_train, Y_train_pred)
  train_r2 = r2(Y_train, Y_train_pred)

  model_rmse = rmse(Y_test, Y_pred)
  model_r2 = r2(Y_test, Y_pred)


  print("Final Weights: ", w_optimal)
  print("Cost History (First 10 iterations): ", cost_history[:10])
  print("Model RMSE:", model_rmse)
  print("Model R2:", model_r2)

  print("\nTraining RMSE:", train_rmse)
  print("Training R2:", train_r2)


  if model_rmse > train_rmse * 1.2:
    # multiplying it by 1.2 signifies the gap between training data and test data
    print("Model is overfitting")
  elif train_rmse > model_rmse * 1.2:
    print("Model may be underfitting")
  else:
    print("Model performance is acceptable")

if __name__ == "__main__":
  main()




Final Weights:  [0.34811659 0.64614558]
Cost History (First 10 iterations):  [2013.165570783755, 1640.286832599692, 1337.0619994901585, 1090.4794892850578, 889.9583270083234, 726.8940993009545, 594.2897260808594, 486.4552052951635, 398.7634463599484, 327.4517147324688]
Model RMSE: 5.2798239764188635
Model R2: 0.8886354462786421

Training RMSE: 5.128473455543202
Training R2: 0.8843826546696121
Model performance is acceptable
