Problem 1 : Array Creation

In [ ]:
# Problem - 1: Array Creation

import numpy as np
#1
array_2d = np.empty((2,2))
print(f"Empty Array(2X2):\n{array_2d}\nDimension: {array_2d.ndim}\nData type: {array_2d.dtype}\n")
print()

#2
array_1 = np.ones((4,2))
print("Array(4X2): ")
print(array_1)
print()

#3
array_2 = np.full((4,2), fill_value = 555)
print("Array with shape and type: ")
print(array_2)
print()

#4
array_4 = np.zeros_like(array_2)
print("New Array with zeros: ")
print(array_4)
print()

#5
array_5 = np.ones_like(array_4)
print("New Array with ones: ")
print(array_5)
print()

#6
new_list = [1,2,3,4]
array_list = np.array(new_list)
print("List -> Array:")
print(array_list)

Empty Array(2X2):
[[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]
Dimension: 2
Data type: float64


Array(4X2): 
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Array with shape and type: 
[[555 555]
 [555 555]
 [555 555]
 [555 555]]

New Array with zeros: 
[[0 0]
 [0 0]
 [0 0]
 [0 0]]

New Array with ones: 
[[1 1]
 [1 1]
 [1 1]
 [1 1]]

List -> Array:
[1 2 3 4]


Problem 2 : Array Manipulation: Numerical Ranges and Array Indexing

In [3]:
# Problem - 2 : Array Manipulation: Numerical Ranges and Array Indexing

import numpy as np

#1
array_1 = np.arange(10,49)
print("Array with range (10-49)")
print(array_1)
print()

#2
array_2 = np.arange(9).reshape((3,3))
print("Array with range (0-8) & size 3X3")
print(array_2)
print()

#3
array_3 = np.eye(3,3)
print("Identity 3X3 matrix")
print(array_3)
print()

#4
array_4 = np.random.rand(30)
mean = np.mean(array_4)
print("Random aray (size: 30)")
print(array_4)
print("Mean of the array: ",mean)
print()

#5
array_5 = np.random.rand(10,10)
max_value = np.max(array_5)
min_value = np.min(array_5)
print("Random array (size: 10X10)")
print(array_5)
print("Maximum value: ",max_value)
print("Minimum value: ",min_value)
print()

#6
array_6 = np.zeros(10)
print("Zero array (size:10)")
print(array_6)

array_6[4] = 1
print("Updated array with fifth value 1")
print(array_6)
print()

#7
arr = [1,2,0,0,4,0]
print("Given array")
print(arr)
array_7 = np.flip(arr)
print("Reversed")
print(array_7)
print()

#8
array1 = [[1,0,0,1],[1,2,3,4]]
print(array1)
print()
arr1 = np.pad(array1, pad_width=1, mode='constant', constant_values=1)
print("2-dimension array with border 1")
print(arr1)
print()


Array with range (10-49)
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]

Array with range (0-8) & size 3X3
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Identity 3X3 matrix
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random aray (size: 30)
[0.29814207 0.01955648 0.97930342 0.01591601 0.01735151 0.78749363
 0.90325048 0.51062037 0.84973657 0.9577911  0.85011391 0.58729017
 0.2928505  0.21187995 0.4150156  0.47058228 0.65444926 0.20656518
 0.51102619 0.14512654 0.51078191 0.1326108  0.92331765 0.16407946
 0.84358071 0.09766039 0.28293729 0.24996781 0.44008417 0.33044342]
Mean of the array:  0.45531749493045215

Random array (size: 10X10)
[[0.49326896 0.20337159 0.95195452 0.34491264 0.33320569 0.77408654
  0.98615682 0.9949066  0.01007825 0.11208359]
 [0.73702471 0.71857721 0.41334048 0.61331827 0.33807159 0.48056892
  0.80837027 0.12374245 0.55921384 0.59532011]
 [0.89832096 0.96044389 0.10164454 0.95152018 0.94493228 0.72486586
  0.0324

In [4]:
#9 : CheckerBoard Pattern

#initialize 8X7  array filled with zeros
arr = np.zeros((8,7))

#(1::2) -> take every second element from rows starting from index 1 -> (1,3,5,7)
#(::2) -> take every element from column from index 0 -> (0,2,4,6)
arr[1::2, ::2] = 1

#(::2) -> take every second element from row from index 0 -> (0,2,4,6)
#(1::2) -> take every element from column from index 0 -> (1,3,5,7)
arr[::2, 1::2] = 1

#print out the result
print("Checkerboard pattern(8X8)")
print(arr)


Checkerboard pattern(8X8)
[[0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1.]]


Problem 3 : Array Operations

In [ ]:
# Problem -3 : Array Operations

#1
x = np.array([[1,2],[3,5]])
y = np.array([[5,6], [7,8]])
print("Array X")
print(x)
print("Array Y")
print(y)

add1 = np.add(x,y)
print("Sum of X and Y:")
print(add1)

Array X
[[1 2]
 [3 5]]
Array Y
[[5 6]
 [7 8]]
Sum of X and Y
[[ 6  8]
 [10 13]]


In [ ]:
#2
x = np.array([[1,2],[3,5]])
y = np.array([[5,6], [7,8]])

sub1 = np.subtract(x,y)
print("Subtraction between X and Y:")
print(sub1)


Subtraction between X and Y
[[-4 -4]
 [-4 -3]]


In [ ]:
#3
x = np.array([[1,2],[3,5]])
mul1 = np.multiply(2, x)
print("Multiplying array-X by 2: ")
print(mul1)

Multiplying array-X by 2: 
[[ 2  4]
 [ 6 10]]


In [ ]:
#4
x = np.array([[1,2],[3,5]])
square = np.square(x)
print("Square of array-X: ")
print(square)

Square of array-X: 
[[ 1  4]
 [ 9 25]]


In [ ]:
#5
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
dot1 = np.dot(x,y)
print("Dot product between X and Y:")
print(dot1)

v = np.array([9,10])
w = np.array([11,12])
dot2 = np.dot(v,w)
print("Dot product between V and W:")
print(dot2)

dot3 = np.dot(x,v)
print("Dot product between X and V:")
print(dot3)

Dot product between X and Y:
[[19 22]
 [50 58]]
Dot product between V and W:
219
Dot product between X and V:
[29 77]


In [ ]:
#6
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

concate1 = np.concatenate((x,y), axis = 1)
print("Concatenate X and Y(along column):")
print(concate1)

concate2 = np.concatenate((v,w), axis = 0)
print("Concatenate V and W(along column):")
print(concate2)

Concatenate X and Y(along column):
[[1 2 5 6]
 [3 5 7 8]]
Concatenate V and W(along column):
[ 9 10 11 12]


In [ ]:
#8
x = np.array([[1,2],[3,5]])
v = np.array([9,10])
concate3 = np.concatenate((x,v))

#ValueError: all the input arrays must have same number of dimensions
#here, x array has 2-dimensions while v has a 1-dimension

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Problem 4 : Matrix Operations

In [ ]:
#Problem - 4 : Matrix Operations

#1 : Prove A*A^(-1) = I

A = np.array([[3,4], [7,8]])
B = np.array([[5,3], [2,1]])

inverse_A = np.linalg.inv(A)

dot_A = np.dot(A, inverse_A)

I = np.eye(A.shape[0])

check = np.allclose(dot_A, I)

print("Matrix A:")
print(A)
print("\nInverse of A:")
print(inverse_A)
print("\nA * A^(-1):")
print(dot_A)
print("\nIs A * A^(-1) equal to Identity matrix?:", check)



Matrix A:
[[3 4]
 [7 8]]

Inverse of A:
[[-2.    1.  ]
 [ 1.75 -0.75]]

A * A^(-1):
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

Is A * A^(-1) equal to Identity matrix?: True


In [ ]:
#2 : Prove A*B != B*A

A = np.array([[3,4], [7,8]])
B = np.array([[5,3], [2,1]])

dot_AB = np.dot(A, B)

dot_BA = np.dot(B, A)

check = np.array_equal(dot_AB, dot_BA)

print("A*B: ")
print(dot_AB)
print("\nB*A: ")
print(dot_BA)
print("\nIs A*B equal to B*A? ",check)


A*B: 
[[23 13]
 [51 29]]

B*A: 
[[36 44]
 [13 16]]

Is A*B equal to B*A?  False


In [ ]:
#3 : Prove (A*B)^T = (B^T)*(A^T)

A = np.array([[3,4], [7,8]])
B = np.array([[5,3], [2,1]])

transpose_AB = np.transpose(np.dot(A,B))

transpose_A = A.T

transpose_B = B.T

transpose_BA = np.dot(transpose_B, transpose_A)

check = np.allclose(transpose_AB, transpose_BA)

print("(A*B)^T :")
print(transpose_AB)

print("\n(B^T)*(A^T):")
print(transpose_BA)

print("\nIs (AB)^T equal to B^T*A^T?: ",check )


(A*B)^T :
[[23 51]
 [13 29]]

(B^T)*(A^T):
[[23 51]
 [13 29]]

Is (AB)^T equal to B^T*A^T?:  True


In [ ]:
# Linear equation : Inverse Methods
# Solve A*X = B  i.e. X = A^(-1)*B

A = np.array([[2,-3,1],
              [1,-1,2],
               [3,1,-1]])

B = np.array([-1,-3,9])

A_inverse = np.linalg.inv(A)

X = np.dot(A_inverse, B)

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nX = A^(-1)*B:")
print(X)

Matrix A:
[[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]

Matrix B:
[-1 -3  9]

X = A^(-1)*B:
[ 2.  1. -2.]
